---
title: "Performing tests & Assumptions"
author: "Charles Alba"
date: "2022-11-05"
output: html_document
---

# Reading and Cleaning data

```{r}
### load library
library(Ecdat)
library(data.table)
#install.packages("naniar")
library(naniar)
library(stringr)
library(dplyr)
library(tidyr)
library(bit64)
library(stargazer)
library(plm)
library(sjPlot)
library(lmtest)
data<-read.csv("data.csv")

# converting columns to their correct format
data$date<-(as.Date((as.character(data$date_range_start)), format='%Y-%m-%d'))
data$county<-str_pad(as.character(data$county), 5, pad = "0")
other_vars<-read.csv("other_vars.csv")
other_vars$Geo_FIPS<-str_pad(as.character(other_vars$Geo_FIPS), 5, pad = "0")
data<-merge(data,other_vars,by.x="county",by.y="Geo_FIPS", all.x=T)

```


# Calculating unhealthy food reliance 

```{r}

# calcularing convenience store reliance 
data$cs<-data$convenient_store_count/((data$convenient_store_count)+(data$grocery_count))

# calculating fast-food reliance 
data$ff<-(data$fast_food_count / (data$fast_food_count+data$full_service_count))

# calculating covid incidence rate. 
data$cv<-((data$monthly_cases)/(data$Total_Population.x))

# taking out only relevant data columns 
data<-data.table(data)
data[is.na(data)] = 0

data$cs[data$cs==0]<-0.00001
data$cs[data$cs==1]<-0.99999
data$ff[data$ff==0]<-0.00001
data$ff[data$ff==1]<-0.99999
data$y_cs<-log(data$cs/(1-data$cs))
data$y_ff<-log(data$ff/(1-data$ff))
```



## Convenience store reliance

```{r}

# Testing multicollinearity for convenience store reliance 

car::vif(lm(y_cs~ cv + percent_black + percent_hispanic + percent_native + percent_asian+population_density+Median_household_income+age_5_to_9+age_10_to_14+age_15_to_17+age_18_to_24+age_25_to_34+age_35_to_44+age_45_to_54+age_55_to_64+age_65_to_74+age_75_to_84+percent_some_college_education_or_more, data=data)) # note: 1.005214 -    8.064772                               

```

```{r}

car::vif(lm(y_cs~ cv + percent_black + percent_hispanic + percent_native + percent_asian+population_density+Median_household_income+age_5_to_9+age_10_to_14+age_15_to_17+age_18_to_24+age_25_to_34+age_35_to_44+age_45_to_54+age_55_to_64+age_65_to_74+age_75_to_84+ High_School_Graduate+Some_College+Bachelor+Master+Professional_degree+Doctorate,data=data)) # 1.005 - 8.533651  
```

```{r}

car::vif(lm(y_cs~ cv + percent_black + percent_hispanic + percent_native + percent_asian+population_density+Median_household_income+age_5_to_9+age_10_to_14+age_15_to_17+age_18_to_24+age_25_to_34+age_35_to_44+age_45_to_54+age_55_to_64+age_65_to_74+age_75_to_84+ High_School_Graduate+Some_College+Bachelor+Master+Professional_degree+Doctorate+Professional_jobs+Healthcare+Protective+Food+Building+Personal+Sales+Administrative+Farming+Construction+Production,data=data)) # note: 1.006 - 9.004
```



## Fast food reliance

```{r}

# Testing multicollinearity for convenience store reliance 

car::vif(lm(y_ff~ cv + percent_black + percent_hispanic + percent_native + percent_asian+population_density+Median_household_income+age_5_to_9+age_10_to_14+age_15_to_17+age_18_to_24+age_25_to_34+age_35_to_44+age_45_to_54+age_55_to_64+age_65_to_74+age_75_to_84+percent_some_college_education_or_more, data=data))

```

```{r}

car::vif(lm(y_ff~ cv + percent_black + percent_hispanic + percent_native + percent_asian+population_density+Median_household_income+Median_age+ High_School_Graduate+Some_College+Bachelor+Master+Professional_degree+Doctorate,data=data))
```

```{r}

car::vif(lm(y_ff~ cv + percent_black + percent_hispanic + percent_native + percent_asian+population_density+Median_household_income+Median_age++ High_School_Graduate+Some_College+Bachelor+Master+Professional_degree+Doctorate+Professional_jobs+Healthcare+Protective+Food+Building+Personal+Sales+Administrative+Farming+Construction+Production,data=data))
```
